#include "settings/localization.hpp"

#include <cstring>

namespace pztrainer::settings {
namespace {

struct Translation {
    const char* zh;
    const char* en;
    const char* ru;
    const char* de;
};

Language g_language = Language::Chinese;

constexpr Translation kTranslations[]{
    {"自瞄", "AIMBOT", "АВТОПРИЦЕЛ", "AIMBOT"},
    {"视觉", "VISUALS", "ВИЗУАЛ", "VISUALS"},
    {"常用", "COMMON", "ОБЩЕЕ", "ALLGEMEIN"},
    {"视觉 ESP", "Visual ESP", "Визуальный ESP", "Visual ESP"},
    {"世界视觉", "World Visuals", "Визуал мира", "Weltvisuals"},
    {"角色状态", "Character", "Персонаж", "Charakter"},
    {"物品生成", "Item Generator", "Создание предметов", "Item-Generator"},
    {"技能经验", "Skills & XP", "Навыки и опыт", "Fertigkeiten & EP"},
    {"载具控制", "Vehicle Control", "Управление транспортом", "Fahrzeugsteuerung"},
    {"世界交互", "World Interaction", "Взаимодействие с миром", "Weltinteraktion"},
    {"角色创建", "Character Creation", "Создание персонажа", "Charaktererstellung"},
    {"角色", "CHARACTER", "ПЕРСОНАЖ", "CHARAKTER"},
    {"世界", "WORLD", "МИР", "WELT"},
    {"工具", "TOOLS", "ИНСТРУМЕНТЫ", "WERKZEUGE"},
    {"世界时间", "World Time", "Время мира", "Weltzeit"},
    {"设置", "Settings", "Настройки", "Einstellungen"},
    {"本地玩家", "Local Player", "Локальный игрок", "Lokaler Spieler"},
    {"本软件是免费的，如果你是购买的，那么你就被骗了。", "This software is free. If you paid for it, you were scammed.", "Эта программа бесплатна. Если вы за неё заплатили, вас обманули.", "Diese Software ist kostenlos. Wenn du dafür bezahlt hast, wurdest du betrogen."},
    {"搜索功能...", "Search features...", "Поиск функций...", "Funktionen suchen..."},
    {"没有匹配功能", "No matching features", "Функции не найдены", "Keine Funktion gefunden"},
    {"辅助瞄准", "Legit Aim", "Легитный прицел", "Legit-Aim"},
    {"启用辅助瞄准", "Enable Legit Aim", "Включить легит", "Legit-Aim aktivieren"},
    {"自动辅助瞄准", "Automatic Aim", "Автоприцел", "Automatisch zielen"},
    {"瞄准僵尸", "Target Zombies", "Целиться в зомби", "Zombies anvisieren"},
    {"瞄准 PVP 玩家", "Target PVP Players", "Целиться в PVP", "PVP-Spieler anvisieren"},
    {"检测墙壁", "Wall Check", "Проверка стен", "Wandprüfung"},
    {"优先站立僵尸", "Prefer Upright Zombies", "Приоритет стоящих", "Stehende bevorzugen"},
    {"瞄准范围", "Aim Range", "Дальность прицела", "Zielreichweite"},
    {"瞄准修正", "Aim Tuning", "Настройка прицела", "Zielanpassung"},
    {"移除视觉后坐力", "Remove Visual Recoil", "Убрать визуальную отдачу", "Visuellen Rückstoß entfernen"},
    {"自瞄平滑", "Aim Smoothing", "Плавность", "Zielglättung"},
    {"命中精度", "Hit Accuracy", "Точность", "Treffergenauigkeit"},
    {"伤害偏好阈值", "Damage Preference", "Порог урона", "Schadenspräferenz"},
    {"暴力瞄准", "Rage Aim", "Rage-прицел", "Rage-Aim"},
    {"启用 Rage", "Enable Rage", "Включить Rage", "Rage aktivieren"},
    {"自动瞄准", "Automatic Aim", "Автоприцел", "Automatisch zielen"},
    {"自动急停", "Automatic Stop", "Автостоп", "Auto-Stopp"},
    {"自动开枪", "Automatic Fire", "Автоогонь", "Automatisch feuern"},
    {"静默瞄准（不移动鼠标）", "Silent Aim (No Mouse Movement)", "Тихий прицел (без движения мыши)", "Silent Aim (keine Mausbewegung)"},
    {"不移动鼠标或原版准星；人物仍会在射击时正确转向 Rage 目标。关闭后会移动鼠标到目标位置。魔法子弹开启时始终保持静默。", "Does not move the mouse or vanilla reticle; the character still turns toward the Rage target when firing. When disabled, the mouse moves to the target position. Magic Bullet always remains silent.", "Не перемещает мышь или обычный прицел; персонаж всё равно поворачивается к цели Rage при стрельбе. Если выключено, мышь перемещается к цели. Волшебная пуля всегда остаётся тихой.", "Bewegt weder Maus noch Original-Fadenkreuz; die Figur dreht sich beim Schießen weiterhin zum Rage-Ziel. Wenn deaktiviert, bewegt sich die Maus zum Ziel. Magische Kugel bleibt immer lautlos."},
    {"魔法子弹（实验）", "Magic Bullet (Experimental)", "Волшебная пуля (эксперимент)", "Magische Kugel (experimentell)"},
    {"攻击范围", "Attack Range", "Дальность атаки", "Angriffsreichweite"},
    {"武器修正", "Weapon Tuning", "Настройка оружия", "Waffenanpassung"},
    {"无扩散", "No Spread", "Без разброса", "Keine Streuung"},
    {"无视觉后坐力", "No Visual Recoil", "Без визуальной отдачи", "Kein visueller Rückstoß"},
    {"最低伤害", "Minimum Damage", "Мин. урон", "Mindestschaden"},
    {"最高伤害", "Maximum Damage", "Макс. урон", "Maximalschaden"},
    {"射击模式", "Fire Mode", "Режим огня", "Feuermodus"},
    {"DT 双发模式", "Double Tap", "Двойной выстрел", "Double Tap"},
    {"武器预设", "Weapon Presets", "Профили оружия", "Waffenprofile"},
    {"全局", "Global", "Общие", "Global"},
    {"手枪", "Pistol", "Пистолет", "Pistole"},
    {"霰弹枪", "Shotgun", "Дробовик", "Schrotflinte"},
    {"冲锋枪", "SMG", "Пистолет-пулемёт", "Maschinenpistole"},
    {"步枪", "Rifle", "Винтовка", "Gewehr"},
    {"狙击枪", "Sniper Rifle", "Снайперская винтовка", "Scharfschützengewehr"},
    {"未知", "Unknown", "Неизвестно", "Unbekannt"},
    {"僵尸", "Zombies", "Зомби", "Zombies"},
    {"玩家", "Players", "Игроки", "Spieler"},
    {"动物", "Animals", "Животные", "Tiere"},
    {"载具", "Vehicles", "Транспорт", "Fahrzeuge"},
    {"启用僵尸透视", "Enable Zombie ESP", "Включить ESP зомби", "Zombie-ESP aktivieren"},
    {"启用玩家透视", "Enable Player ESP", "Включить ESP игроков", "Spieler-ESP aktivieren"},
    {"启用动物透视", "Enable Animal ESP", "Включить ESP животных", "Tier-ESP aktivieren"},
    {"启用载具透视", "Enable Vehicle ESP", "Включить ESP транспорта", "Fahrzeug-ESP aktivieren"},
    {"显示方框", "Show Boxes", "Показывать рамки", "Boxen anzeigen"},
    {"显示名称", "Show Names", "Показывать имена", "Namen anzeigen"},
    {"显示距离", "Show Distance", "Показывать дистанцию", "Distanz anzeigen"},
    {"显示骨骼", "Show Skeleton", "Показывать скелет", "Skelett anzeigen"},
    {"显示血条", "Show Health Bar", "Показывать здоровье", "Lebensleiste anzeigen"},
    {"方向箭头", "Direction Arrow", "Стрелка направления", "Richtungspfeil"},
    {"标记服务器管理员", "Highlight Server Admins", "Выделять администраторов сервера", "Serveradministratoren hervorheben"},
    {"显示车辆详情", "Vehicle Details", "Данные транспорта", "Fahrzeugdetails"},
    {"显示发动机状态条", "Engine Status Bar", "Состояние двигателя", "Motorstatusleiste"},
    {"最大显示距离", "Maximum Distance", "Макс. дистанция", "Maximale Distanz"},
    {"效果", "Effects", "Эффекты", "Effekte"},
    {"伪白天", "Fake Daylight", "Искусственный день", "Künstliches Tageslicht"},
    {"暗区增亮", "Brighten Darkness", "Осветлить тьму", "Dunkelheit aufhellen"},
    {"360°全向视野", "360° Vision", "Обзор 360°", "360°-Sicht"},
    {"移除未探索黑幕", "Reveal Unexplored", "Открыть неизведанное", "Unentdecktes aufdecken"},
    {"解锁世界地图迷雾", "Reveal World Map", "Открыть карту мира", "Weltkarte aufdecken"},
    {"只解除本地世界地图的未探索遮罩，单机和联机均可使用。关闭后恢复原来的地图迷雾设置。", "Only removes the local world map's unexplored overlay. Works in single-player and multiplayer, and restores the original setting when disabled.", "Убирает только локальную маску неизведанного на карте мира. Работает в одиночной и сетевой игре; после отключения исходная настройка восстанавливается.", "Entfernt nur die lokale Unentdeckt-Maske der Weltkarte. Funktioniert im Einzel- und Mehrspielermodus und stellt beim Deaktivieren die ursprüngliche Einstellung wieder her."},
    {"世界地图迷雾桥接尚未初始化", "The world-map reveal bridge is not initialized", "Мост открытия карты мира не инициализирован", "Die Weltkarten-Bridge ist nicht initialisiert"},
    {"世界地图迷雾保持原样", "World-map fog unchanged", "Туман карты мира не изменён", "Weltkartennebel unverändert"},
    {"请打开世界地图以解锁地图迷雾", "Open the world map to reveal it", "Откройте карту мира, чтобы убрать туман", "Öffne die Weltkarte, um sie aufzudecken"},
    {"世界地图迷雾已在本地解除", "World-map fog removed locally", "Туман карты мира удалён локально", "Weltkartennebel lokal entfernt"},
    {"解除世界地图迷雾失败", "Failed to remove world-map fog", "Не удалось убрать туман карты мира", "Weltkartennebel konnte nicht entfernt werden"},
    {"地图显示其他玩家", "Show Other Players on Maps", "Показывать других игроков на карте", "Andere Spieler auf Karten anzeigen"},
    {"调用原版大地图和小地图玩家标记。可显示客户端已经同步到的其他玩家；服务器未下发的位置无法显示。大地图或小地图内的“控制玩家”选项需要保持开启。", "Uses the vanilla player markers on the world map and mini-map. It can show other players already synchronized to this client; positions withheld by the server cannot be shown. Keep the map's Remote Players option enabled.", "Использует исходные метки игроков на карте мира и мини-карте. Показываются только игроки, уже синхронизированные с клиентом; позиции, не отправленные сервером, показать нельзя. Оставьте параметр отображения удалённых игроков включённым.", "Verwendet die originalen Spielermarkierungen auf Welt- und Minikarte. Angezeigt werden nur Spieler, die bereits mit diesem Client synchronisiert sind; vom Server nicht übermittelte Positionen können nicht angezeigt werden. Die Kartenoption für entfernte Spieler muss aktiviert bleiben."},
    {"地图玩家标记桥接尚未初始化", "The map-player marker bridge is not initialized", "Мост меток игроков на карте не инициализирован", "Die Karten-Spielermarkierungs-Bridge ist nicht initialisiert"},
    {"进入联机服务器后显示地图玩家标记", "Join a multiplayer server to show map-player markers", "Войдите на сетевой сервер, чтобы показать метки игроков", "Tritt einem Mehrspieler-Server bei, um Spielermarkierungen anzuzeigen"},
    {"地图玩家标记待命", "Map-player markers ready", "Метки игроков на карте готовы", "Karten-Spielermarkierungen bereit"},
    {"无法启用原版地图玩家标记", "Failed to enable vanilla map-player markers", "Не удалось включить исходные метки игроков на карте", "Originale Karten-Spielermarkierungen konnten nicht aktiviert werden"},
    {"已启用，等待服务器同步其他玩家", "Enabled; waiting for other players to be synchronized", "Включено; ожидание синхронизации других игроков", "Aktiviert; warte auf die Synchronisierung anderer Spieler"},
    {"已使用原版地图标记显示已同步玩家", "Showing synchronized players with vanilla map markers", "Синхронизированные игроки показаны исходными метками карты", "Synchronisierte Spieler werden mit originalen Kartenmarkierungen angezeigt"},
    {"天气选项", "Weather", "Погода", "Wetter"},
    {"枪口射线", "Weapon Ray", "Луч оружия", "Waffenstrahl"},
    {"显示枪口射线", "Show Weapon Ray", "Показывать луч", "Waffenstrahl anzeigen"},
    {"射线颜色", "Ray Color", "Цвет луча", "Strahlfarbe"},
    {"生命保护", "Health Protection", "Защита здоровья", "Lebensschutz"},
    {"无限生命", "Infinite Health", "Бесконечное здоровье", "Unendlich Leben"},
    {"无敌模式", "Invincibility", "Неуязвимость", "Unverwundbarkeit"},
    {"人物穿墙", "No-clip", "Прохождение сквозь стены", "Durch Wände gehen"},
    {"人物移动桥接尚未初始化。", "The player movement bridge is not initialized.", "Мост движения игрока не инициализирован.", "Die Spielerbewegungs-Bridge ist nicht initialisiert."},
    {"无限负重", "Unlimited Carry", "Неограниченная переноска", "Unbegrenztes Tragen"},
    {"最大负重倍率", "Maximum Carry Multiplier", "Множитель максимальной нагрузки", "Maximale Tragekapazität"},
    {"无疲劳", "No Fatigue", "Без усталости", "Keine Ermüdung"},
    {"无恐慌", "No Panic", "Без паники", "Keine Panik"},
    {"无饥饿", "No Hunger", "Без голода", "Kein Hunger"},
    {"无口渴", "No Thirst", "Без жажды", "Kein Durst"},
    {"移除负面心情", "Remove Negative Moodles", "Убрать негативные настроения", "Negative Moodles entfernen"},
    {"免疫感染/咬伤", "Infection/Bite Immunity", "Иммунитет к инфекции и укусам", "Immunität gegen Infektion/Bisse"},
    {"当前联机角色缺少 CanModifyBodyStats 权限，服务器不会接受该属性同步。", "The current multiplayer role lacks CanModifyBodyStats, so the server will not accept this stat sync.", "У текущей сетевой роли нет права CanModifyBodyStats, поэтому сервер не примет синхронизацию этой характеристики.", "Der aktuellen Mehrspielerrolle fehlt CanModifyBodyStats; der Server akzeptiert diese Attribut-Synchronisierung daher nicht."},
    {"当前会话没有可用的口渴同步路径。", "No thirst synchronization route is available in the current session.", "В текущем сеансе нет доступного способа синхронизации жажды.", "In der aktuellen Sitzung ist kein Weg zur Durst-Synchronisierung verfügbar."},
    {"当前会话没有可用的伤势同步路径。", "No injury synchronization route is available in the current session.", "В текущем сеансе нет доступного способа синхронизации травм.", "In der aktuellen Sitzung ist kein Weg zur Verletzungs-Synchronisierung verfügbar."},
    {"只清理可编辑的负面角色属性；不会修改体温、负重或实际伤口。", "Only clears editable negative character stats; temperature, carry weight, and physical wounds are not changed.", "Очищает только доступные негативные характеристики; температура, переносимый вес и физические раны не изменяются.", "Löscht nur bearbeitbare negative Charakterwerte; Temperatur, Tragegewicht und körperliche Wunden werden nicht verändert."},
    {"清除尸毒感染、假感染、普通伤口感染和咬伤状态，并通过 PlayerDamage 同步；不代表服务器不会产生新的伤害事件。", "Clears zombie infection, fake infection, wound infection, and bite state, then syncs through PlayerDamage; it does not prevent the server from creating new damage events.", "Очищает зомби-инфекцию, ложную инфекцию, инфекцию ран и укусы, затем синхронизирует через PlayerDamage; сервер всё ещё может создать новое повреждение.", "Entfernt Zombie-Infektion, Schein-Infektion, Wundinfektion und Bissstatus und synchronisiert dies über PlayerDamage; neue Schadensereignisse des Servers werden dadurch nicht verhindert."},
    {"启用后，最大负重等于游戏当前原版最大负重乘以此倍率。倍率不会逐帧重复叠加；联机同步只在目标整数变化时发送。", "When enabled, maximum carry weight equals the game's current vanilla maximum multiplied by this value. The multiplier is not compounded every frame; multiplayer sync is sent only when the integer target changes.", "После включения максимальная нагрузка равна текущему исходному максимуму игры, умноженному на это значение. Множитель не накапливается каждый кадр; сетевая синхронизация отправляется только при изменении целевого целого значения.", "Wenn aktiviert, entspricht die maximale Traglast dem aktuellen unveränderten Spielwert multipliziert mit diesem Faktor. Der Faktor wird nicht pro Frame erneut multipliziert; die Mehrspieler-Synchronisierung erfolgt nur bei Änderung des ganzzahligen Zielwerts."},
    {"无限负重桥接尚未初始化", "The unlimited-carry bridge is not initialized", "Мост неограниченной переноски не инициализирован", "Die Unlimited-Carry-Bridge ist nicht initialisiert"},
    {"无限负重运行中", "Unlimited carry is active", "Неограниченная переноска активна", "Unbegrenztes Tragen ist aktiv"},
    {"无限负重待命", "Unlimited carry ready", "Неограниченная переноска готова", "Unbegrenztes Tragen bereit"},
    {"修改负重状态失败", "Failed to change carry state", "Не удалось изменить состояние переноски", "Tragestatus konnte nicht geändert werden"},
    {"地图点击传送", "Map Click Teleport", "Телепорт по карте", "Karten-Teleport"},
    {"打开世界地图后，按住 Alt 并点击鼠标左键。联机服务器仍可能因速度或穿墙检查踢出玩家。", "Open the world map, then hold Alt and left-click. Multiplayer servers may still kick for speed or no-clip checks.", "Откройте карту мира, затем удерживайте Alt и щёлкните левой кнопкой. Сервер всё ещё может исключить игрока за скорость или прохождение сквозь стены.", "Öffne die Weltkarte, halte Alt und klicke links. Mehrspieler-Server können weiterhin wegen Geschwindigkeits- oder No-Clip-Prüfungen trennen."},
    {"地图传送桥接尚未初始化", "The map teleport bridge is not initialized", "Мост телепорта по карте не инициализирован", "Die Karten-Teleport-Bridge ist nicht initialisiert"},
    {"地图传送待命", "Map teleport ready", "Телепорт по карте готов", "Karten-Teleport bereit"},
    {"等待进入存档并创建玩家", "Waiting for a loaded player", "Ожидание загрузки игрока", "Warte auf einen geladenen Spieler"},
    {"请打开世界地图", "Open the world map", "Откройте карту мира", "Öffne die Weltkarte"},
    {"在世界地图上按住 Alt 并点击鼠标左键", "Hold Alt and left-click on the world map", "Удерживайте Alt и щёлкните левой кнопкой по карте мира", "Halte Alt und klicke links auf die Weltkarte"},
    {"无法读取世界地图坐标", "Unable to read world-map coordinates", "Не удалось прочитать координаты карты мира", "Weltkartenkoordinaten konnten nicht gelesen werden"},
    {"所选位置不在当前世界地图范围内", "The selected position is outside the current world map", "Выбранная позиция находится за пределами текущей карты мира", "Die gewählte Position liegt außerhalb der aktuellen Weltkarte"},
    {"已修改玩家位置并发送联机位置更新", "Player position changed and multiplayer update sent", "Позиция игрока изменена, сетевое обновление отправлено", "Spielerposition geändert und Mehrspieler-Aktualisierung gesendet"},
    {"已修改玩家位置", "Player position changed", "Позиция игрока изменена", "Spielerposition geändert"},
    {"修改玩家位置失败", "Failed to change player position", "Не удалось изменить позицию игрока", "Spielerposition konnte nicht geändert werden"},
    {"地图传送冷却中", "Map teleport is cooling down", "Телепорт по карте перезаряжается", "Karten-Teleport lädt ab"},
    {"下一次传送需要等待 %u 秒", "Wait %u seconds before the next teleport", "До следующего телепорта: %u с", "Nächster Teleport in %u Sekunden"},
    {"体力与装备", "Stamina & Equipment", "Выносливость и вещи", "Ausdauer & Ausrüstung"},
    {"快速恢复体力", "Fast Stamina Recovery", "Быстрое восстановление", "Schnelle Ausdauer"},
    {"联机休息补偿／快速体力", "Multiplayer Rest Compensation / Fast Stamina", "Компенсация отдыха / Быстрая выносливость", "Mehrspieler-Ruheausgleich / Schnelle Ausdauer"},
    {"联机休息补偿尚未初始化", "Multiplayer rest compensation is not initialized", "Компенсация отдыха не инициализирована", "Mehrspieler-Ruheausgleich ist nicht initialisiert"},
    {"联机休息补偿待命", "Multiplayer rest compensation ready", "Компенсация отдыха готова", "Mehrspieler-Ruheausgleich bereit"},
    {"等待联机玩家对象", "Waiting for the multiplayer player object", "Ожидание сетевого объекта игрока", "Warte auf das Mehrspieler-Spielerobjekt"},
    {"载具内不提交休息补偿", "Rest compensation is paused in vehicles", "В транспорте компенсация отдыха приостановлена", "Ruheausgleich ist in Fahrzeugen pausiert"},
    {"联机休息补偿已就绪；攻击消耗会自然恢复", "Rest compensation is ready; attack exertion recovers naturally", "Компенсация отдыха готова; затраты атаки восстанавливаются естественно", "Ruheausgleich ist bereit; Angriffsverbrauch erholt sich natürlich"},
    {"已提交普通移动状态，服务器按自然恢复处理", "Submitted normal movement state for server-side natural recovery", "Отправлено обычное состояние движения для естественного восстановления сервером", "Normaler Bewegungsstatus für serverseitige natürliche Erholung gesendet"},
    {"联机休息补偿提交失败，等待重试", "Rest compensation submission failed; waiting to retry", "Не удалось отправить компенсацию отдыха; ожидание повтора", "Ruheausgleich konnte nicht gesendet werden; neuer Versuch folgt"},
    {"手持装备无限耐久", "Infinite Held Durability", "Бесконечная прочность", "Unendliche Haltbarkeit"},
    {"无限子弹", "Infinite Ammo", "Бесконечные патроны", "Unendlich Munition"},
    {"枪械防卡壳", "No Weapon Jams", "Без заклинивания оружия", "Keine Waffenhemmung"},
    {"仅对当前主手远程枪械生效。开启时把原版卡壳概率临时设为 0；切枪或关闭后恢复该枪原值。若枪械已经卡壳，会清除状态并通过 SyncHandWeaponFields 同步服务器。不会修改弹药、射速、装填或耐久，普通联机账号可用。", "Only affects the ranged weapon in the primary hand. While enabled, its vanilla jam chance is temporarily set to zero and restored when switching weapons or disabling the feature. An existing jam is cleared and synchronized through SyncHandWeaponFields. Ammo, fire rate, reload speed, and durability are not changed; no administrator permission is required.", "Действует только на огнестрельное оружие в основной руке. Пока функция включена, исходный шанс заклинивания временно равен нулю и восстанавливается при смене оружия или выключении. Уже возникшее заклинивание снимается и синхронизируется через SyncHandWeaponFields. Боеприпасы, темп стрельбы, перезарядка и прочность не изменяются; права администратора не нужны.", "Wirkt nur auf die Fernwaffe in der Haupthand. Während die Funktion aktiv ist, wird ihre originale Ladehemmungswahrscheinlichkeit vorübergehend auf null gesetzt und beim Waffenwechsel oder Abschalten wiederhergestellt. Eine vorhandene Hemmung wird beseitigt und über SyncHandWeaponFields synchronisiert. Munition, Feuerrate, Nachladen und Haltbarkeit bleiben unverändert; Administratorrechte sind nicht erforderlich."},
    {"枪械防卡壳桥接尚未初始化", "The no-jam bridge is not initialized", "Мост защиты от заклинивания не инициализирован", "Die Waffenhemmungs-Bridge ist nicht initialisiert"},
    {"枪械防卡壳待命", "No-jam protection ready", "Защита от заклинивания готова", "Schutz vor Waffenhemmung bereit"},
    {"枪械防卡壳运行中", "No-jam protection active", "Защита от заклинивания активна", "Schutz vor Waffenhemmung aktiv"},
    {"读取枪械卡壳参数失败", "Failed to read weapon jam parameters", "Не удалось прочитать параметры заклинивания", "Waffenhemmungsparameter konnten nicht gelesen werden"},
    {"写入枪械防卡壳参数失败", "Failed to apply no-jam parameters", "Не удалось применить защиту от заклинивания", "Schutzparameter gegen Waffenhemmung konnten nicht angewendet werden"},
    {"清除枪械卡壳状态失败", "Failed to clear the weapon jam", "Не удалось устранить заклинивание", "Waffenhemmung konnte nicht beseitigt werden"},
    {"已清除卡壳并同步服务器", "Weapon jam cleared and synchronized with the server", "Заклинивание устранено и синхронизировано с сервером", "Waffenhemmung beseitigt und mit dem Server synchronisiert"},
    {"本地已清除卡壳，但服务器同步失败", "Weapon jam cleared locally, but server synchronization failed", "Заклинивание устранено локально, но синхронизация с сервером не удалась", "Waffenhemmung lokal beseitigt, aber Serversynchronisierung fehlgeschlagen"},
    {"已清除枪械卡壳", "Weapon jam cleared", "Заклинивание оружия устранено", "Waffenhemmung beseitigt"},
    {"联机战斗与建造", "Multiplayer Combat & Building", "Сетевой бой и строительство", "Mehrspieler-Kampf & Bauen"},
    {"多目标攻击僵尸", "Multi-Hit Zombies", "Атака нескольких зомби", "Mehrere Zombies treffen"},
    {"创造模式／免费建造", "Creative Mode / Free Building", "Творческий режим / бесплатное строительство", "Kreativmodus / kostenloses Bauen"},
    {"使用游戏原版多目标命中列表；服务器仍会检查武器、距离、目标、PVP 规则和反作弊。无需管理权限。如果服务器允许 PVP，附近可攻击玩家也可能进入原版挥击列表。联机实战仍需验证。", "Uses the vanilla multi-hit list; the server still validates the weapon, range, targets, PVP rules, and anti-cheat. No administrator permission is required. If the server allows PVP, nearby attackable players may also enter the vanilla swing list. Live multiplayer testing is still required.", "Использует исходный список множественных попаданий; сервер всё равно проверяет оружие, дистанцию, цели, правила PVP и античит. Права администратора не нужны. Если сервер разрешает PVP, доступные для атаки игроки поблизости также могут попасть в исходный список удара. Требуется проверка в сетевой игре.", "Verwendet die originale Mehrfachtrefferliste; der Server prüft weiterhin Waffe, Reichweite, Ziele, PVP-Regeln und Anti-Cheat. Keine Administratorrechte erforderlich. Wenn der Server PVP erlaubt, können nahe angreifbare Spieler ebenfalls in die originale Trefferliste gelangen. Ein Mehrspieler-Praxistest ist noch erforderlich."},
    {"不刷物品，也不伪造背包材料。仅允许占地 1 格、只生成 1 个结构的建筑免费构建；多格、多层、窗户或复合结构会生成实体幽灵且不可正常拆除，因此会直接禁止构建。无需管理权限。", "Does not spawn items or forge inventory materials. Only structures occupying one tile and creating one object can be built for free. Multi-tile, multi-level, window, and compound structures would create solid ghost objects that cannot be dismantled normally, so construction is blocked. No administrator permission is required.", "Не создаёт предметы и не подделывает материалы в инвентаре. Бесплатно разрешены только постройки, занимающие одну клетку и создающие один объект. Многоклеточные, многоуровневые, оконные и составные конструкции создавали бы твёрдые объекты-призраки, которые нельзя нормально разобрать, поэтому их строительство блокируется. Права администратора не нужны.", "Erzeugt keine Gegenstände und fälscht keine Inventarmaterialien. Kostenlos sind nur Bauten erlaubt, die ein Feld belegen und ein Objekt erzeugen. Mehrfeldrige, mehrstöckige, Fenster- und Verbundstrukturen würden feste Geisterobjekte erzeugen, die sich nicht normal zerlegen lassen; deshalb wird ihr Bau blockiert. Keine Administratorrechte erforderlich."},
    {"多目标攻击桥接尚未初始化", "The multi-hit bridge is not initialized", "Мост множественных попаданий не инициализирован", "Die Mehrfachtreffer-Bridge ist nicht initialisiert"},
    {"多目标攻击已作用于原版命中列表", "Multi-hit is active in the vanilla hit list", "Множественные попадания включены в исходном списке целей", "Mehrfachtreffer ist in der originalen Trefferliste aktiv"},
    {"多目标攻击待命", "Multi-hit ready", "Множественные попадания готовы", "Mehrfachtreffer bereit"},
    {"读取武器群攻选项失败", "Failed to read the weapon multi-hit option", "Не удалось прочитать параметр множественного удара", "Mehrfachtrefferoption der Waffe konnte nicht gelesen werden"},
    {"修改武器群攻选项失败", "Failed to change the weapon multi-hit option", "Не удалось изменить параметр множественного удара", "Mehrfachtrefferoption der Waffe konnte nicht geändert werden"},
    {"免费建造桥接尚未初始化", "The free-building bridge is not initialized", "Мост бесплатного строительства не инициализирован", "Die Gratisbau-Bridge ist nicht initialisiert"},
    {"正在安装单格免费建造转换", "Installing single-tile free-building conversion", "Установка преобразования бесплатного строительства для одной клетки", "Einzelfeld-Gratisbauumwandlung wird installiert"},
    {"正在关闭单格免费建造转换", "Disabling single-tile free-building conversion", "Отключение преобразования бесплатного строительства для одной клетки", "Einzelfeld-Gratisbauumwandlung wird deaktiviert"},
    {"免费建造已启用：仅允许占地一格的单结构建筑", "Free building enabled: single-structure buildings occupying one tile only", "Бесплатное строительство включено: только одиночные постройки на одной клетке", "Gratisbau aktiviert: nur Einzelstrukturen auf einem Feld"},
    {"免费建造待命", "Free building ready", "Бесплатное строительство готово", "Gratisbau bereit"},
    {"状态与效果", "Status & Effects", "Статус и эффекты", "Status & Effekte"},
    {"默认", "Default", "Обычно", "Standard"},
    {"墙后", "Behind Wall", "За стеной", "Hinter Wand"},
    {"视野内", "In View", "В поле зрения", "Im Sichtfeld"},
    {"待机", "Idle", "Ожидание", "Leerlauf"},
    {"行走", "Walk", "Ходьба", "Gehen"},
    {"奔跑", "Run", "Бег", "Laufen"},
    {"扑咬", "Lunge", "Бросок", "Anspringen"},
    {"冲刺", "Sprint", "Спринт", "Sprinten"},
    {"进食", "Feed", "Кормление", "Fressen"},
    {"预览动画", "Preview Animation", "Анимация предпросмотра", "Vorschauanimation"},
    {"远程玩家", "Remote Player", "Удалённый игрок", "Entfernter Spieler"},
    {"%.1f 格", "%.1f tiles", "%.1f клетки", "%.1f Felder"},
    {"玩家模型或动画资源加载失败", "Failed to load player model or animation resources", "Не удалось загрузить модель или анимацию игрока", "Spielermodell oder Animation konnte nicht geladen werden"},
    {"拖动旋转 · 玩家动画与 ESP 预览", "Drag to rotate · Player animation and ESP preview", "Перетаскивайте для вращения · Анимация игрока и ESP", "Zum Drehen ziehen · Spieleranimation und ESP-Vorschau"},
    {"游戏模型或动画资源加载失败", "Failed to load model or animation resources", "Не удалось загрузить модель или анимацию", "Modell- oder Animationsressourcen konnten nicht geladen werden"},
    {"拖动旋转 · 实时动画与 ESP 预览", "Drag to rotate · Live animation and ESP preview", "Перетаскивайте для вращения · Анимация и ESP в реальном времени", "Zum Drehen ziehen · Echtzeitanimation und ESP-Vorschau"},
    {"游戏动物模型加载失败", "Failed to load the game animal model", "Не удалось загрузить модель животного", "Tiermodell des Spiels konnte nicht geladen werden"},
    {"游戏模型：CowBody.x", "Game model: CowBody.x", "Игровая модель: CowBody.x", "Spielmodell: CowBody.x"},
    {"游戏载具模型加载失败", "Failed to load the game vehicle model", "Не удалось загрузить модель транспорта", "Fahrzeugmodell des Spiels konnte nicht geladen werden"},
    {"游戏模型：Vehicles_CarNormal.fbx", "Game model: Vehicles_CarNormal.fbx", "Игровая модель: Vehicles_CarNormal.fbx", "Spielmodell: Vehicles_CarNormal.fbx"},
    {"3D 模型资源加载失败", "Failed to load 3D model resources", "Не удалось загрузить ресурсы 3D-модели", "3D-Modellressourcen konnten nicht geladen werden"},
    {"界面与语言", "Interface & Language", "Интерфейс и язык", "Oberfläche & Sprache"},
    {"界面缩放", "Interface Scale", "Масштаб интерфейса", "Oberflächenskalierung"},
    {"语言", "Language", "Язык", "Sprache"},
    {"菜单呼出按键", "Menu Hotkey", "Клавиша меню", "Menü-Taste"},
    {"请按下新的按键...", "Press a new key...", "Нажмите новую клавишу...", "Neue Taste drücken..."},
    {"按 Esc 取消", "Press Esc to cancel", "Esc — отмена", "Esc zum Abbrechen"},
    {"菜单呼出按键已更新", "Menu hotkey updated", "Клавиша меню обновлена", "Menü-Taste aktualisiert"},
    {"配置管理", "Configuration Manager", "Управление конфигурациями", "Konfigurationsverwaltung"},
    {"配置名称", "Configuration Name", "Имя конфигурации", "Konfigurationsname"},
    {"新建", "New", "Создать", "Neu"},
    {"保存", "Save", "Сохранить", "Speichern"},
    {"加载", "Load", "Загрузить", "Laden"},
    {"刷新", "Refresh", "Обновить", "Aktualisieren"},
    {"配置目录", "Configuration Folder", "Папка конфигураций", "Konfigurationsordner"},
    {"选择目录", "Choose Folder", "Выбрать папку", "Ordner wählen"},
    {"请输入配置名称", "Enter a configuration name", "Введите имя конфигурации", "Konfigurationsnamen eingeben"},
    {"配置已保存", "Configuration saved", "Конфигурация сохранена", "Konfiguration gespeichert"},
    {"配置已加载", "Configuration loaded", "Конфигурация загружена", "Konfiguration geladen"},
    {"配置已创建", "Configuration created", "Конфигурация создана", "Konfiguration erstellt"},
    {"保存目录已更新", "Folder updated", "Папка обновлена", "Ordner aktualisiert"},
    {"中文", "Chinese", "Китайский", "Chinesisch"},
    {"英文", "English", "Английский", "Englisch"},
    {"俄文", "Russian", "Русский", "Russisch"},
    {"德文", "German", "Немецкий", "Deutsch"},
    {"雾效果", "Fog", "Туман", "Nebel"},
    {"降水效果", "Precipitation", "Осадки", "Niederschlag"},
    {"雾强度", "Fog Intensity", "Плотность тумана", "Nebelstärke"},
    {"降水强度", "Precipitation Intensity", "Сила осадков", "Niederschlagsstärke"},
    {"跟随游戏", "Follow Game", "Как в игре", "Spiel folgen"},
    {"强制关闭", "Force Off", "Выключить", "Erzwinge Aus"},
    {"强制开启", "Force On", "Включить", "Erzwinge An"},
    {"强制下雨", "Force Rain", "Принудительный дождь", "Regen erzwingen"},
    {"强制下雪", "Force Snow", "Принудительный снег", "Schnee erzwingen"},
    {"Rage 击中点", "Rage Hit Points", "Точки Rage", "Rage-Treffpunkte"},
    {"Legit 击中点", "Legit Hit Points", "Точки Legit", "Legit-Treffpunkte"},
    {"3D 僵尸预览", "3D Zombie Preview", "3D-просмотр зомби", "3D-Zombievorschau"},
    {"3D 玩家预览", "3D Player Preview", "3D-просмотр игрока", "3D-Spielervorschau"},
    {"3D 动物预览", "3D Animal Preview", "3D-просмотр животного", "3D-Tiervorschau"},
    {"3D 载具预览", "3D Vehicle Preview", "3D-просмотр транспорта", "3D-Fahrzeugvorschau"},
    {"头部", "Head", "Голова", "Kopf"},
    {"颈部", "Neck", "Шея", "Hals"},
    {"胸部", "Chest", "Грудь", "Brust"},
    {"腹部", "Abdomen", "Живот", "Bauch"},
    {"骨盆", "Pelvis", "Таз", "Becken"},
    {"左臂", "Left Arm", "Левая рука", "Linker Arm"},
    {"右臂", "Right Arm", "Правая рука", "Rechter Arm"},
    {"左手", "Left Hand", "Левая кисть", "Linke Hand"},
    {"右手", "Right Hand", "Правая кисть", "Rechte Hand"},
    {"左大腿", "Left Thigh", "Левое бедро", "Linker Oberschenkel"},
    {"右大腿", "Right Thigh", "Правое бедро", "Rechter Oberschenkel"},
    {"左小腿", "Left Calf", "Левая голень", "Linke Wade"},
    {"右小腿", "Right Calf", "Правая голень", "Rechte Wade"},
    {"左脚", "Left Foot", "Левая стопа", "Linker Fuß"},
    {"右脚", "Right Foot", "Правая стопа", "Rechter Fuß"},
    {"上色效果", "Model Effect", "Эффект модели", "Modelleffekt"},
    {"模型高级设置", "Advanced Model Settings", "Настройки модели", "Erweiterte Modelleinstellungen"},
    {"边缘发光", "Edge Glow", "Свечение краёв", "Kantenglühen"},
    {"强制显示上色模型", "Force Colored Model", "Всегда цветная модель", "Gefärbtes Modell erzwingen"},
    {"该页面尚未实现", "This page is not implemented", "Страница ещё не готова", "Diese Seite ist noch nicht implementiert"},
    {"%.0f 格", "%.0f tiles", "%.0f клеток", "%.0f Felder"},
    {"%.0f 秒", "%.0f sec", "%.0f сек", "%.0f Sek"},
    {"技能与熟练度", "Skills & Proficiency", "Навыки", "Fertigkeiten"},
    {"搜索技能名称或 ID", "Search skill name or ID", "Поиск навыка или ID", "Fertigkeit oder ID suchen"},
    {"选择一项技能", "Select a skill", "Выберите навык", "Fertigkeit auswählen"},
    {"没有匹配的技能", "No matching skills", "Навыки не найдены", "Keine Fertigkeit gefunden"},
    {"增加经验", "Experience Amount", "Количество опыта", "Erfahrungsmenge"},
    {"添加经验", "Add Experience", "Добавить опыт", "Erfahrung hinzufügen"},
    {"原版 API 添加经验", "Add Experience (Vanilla API)", "Добавить опыт (оригинальный API)", "Erfahrung hinzufügen (Vanilla-API)"},
    {"安全模式", "Safety Mode", "Безопасный режим", "Sicherheitsmodus"},
    {"启用安全模式", "Enable Safety Mode", "Включить безопасный режим", "Sicherheitsmodus aktivieren"},
    {"安全模式开启时，直接调用原版 API 的高风险功能会被禁用；关闭后仅解锁明确标注的功能。", "When Safety Mode is enabled, high-risk direct vanilla API actions are disabled. Turning it off only unlocks explicitly marked features.", "При включённом безопасном режиме опасные прямые вызовы оригинального API отключены. После отключения разблокируются только явно отмеченные функции.", "Im Sicherheitsmodus sind riskante direkte Aufrufe der Vanilla-API deaktiviert. Nach dem Ausschalten werden nur ausdrücklich markierte Funktionen freigeschaltet."},
    {"安全模式已开启。请到设置中关闭安全模式后使用原版 API。", "Safety Mode is enabled. Turn it off in Settings before using the vanilla API.", "Безопасный режим включён. Отключите его в настройках перед использованием оригинального API.", "Der Sicherheitsmodus ist aktiviert. Deaktiviere ihn in den Einstellungen, bevor du die Vanilla-API verwendest."},
    {"等待玩家对象准备完成。", "Waiting for the player object to become ready.", "Ожидание готовности объекта игрока.", "Warte, bis das Spielerobjekt bereit ist."},
    {"等待玩家对象", "Waiting for the player object", "Ожидание объекта игрока", "Warte auf das Spielerobjekt"},
    {"请先进入单机存档", "Enter a single-player save first", "Сначала войдите в одиночное сохранение", "Öffne zuerst einen Einzelspieler-Spielstand"},
    {"Lua 目录", "Lua Folder", "Папка Lua", "Lua-Ordner"},
    {"Lua 目录已更新", "Lua folder updated", "Папка Lua обновлена", "Lua-Ordner aktualisiert"},
    {"选择 Lua 文件", "Select Lua File", "Выбрать файл Lua", "Lua-Datei auswählen"},
    {"未加载", "Not Loaded", "Не загружен", "Nicht geladen"},
    {"正在加载", "Loading", "Загрузка", "Wird geladen"},
    {"已加载", "Loaded", "Загружен", "Geladen"},
    {"正在停止", "Stopping", "Остановка", "Wird beendet"},
    {"加载错误", "Load Error", "Ошибка загрузки", "Ladefehler"},
    {"修改时间", "Modified", "Изменён", "Geändert"},
    {"停止", "Stop", "Остановить", "Stoppen"},
    {"编辑", "Edit", "Редактировать", "Bearbeiten"},
    {"重载", "Reload", "Перезагрузить", "Neu laden"},
    {"自动重载", "Auto Reload", "Автоперезагрузка", "Automatisch neu laden"},
    {"复制", "Duplicate", "Дублировать", "Duplizieren"},
    {"确定删除这个 Lua 文件吗？此操作无法撤销。", "Delete this Lua file? This cannot be undone.", "Удалить этот файл Lua? Это действие нельзя отменить.", "Diese Lua-Datei löschen? Dies kann nicht rückgängig gemacht werden."},
    {"目录中没有 Lua 文件。可以选择文件直接加载，或在设置中更改 Lua 目录。", "There are no Lua files in this folder. Select a file to load it directly, or change the Lua folder in Settings.", "В папке нет файлов Lua. Выберите файл для прямой загрузки или измените папку Lua в настройках.", "In diesem Ordner befinden sich keine Lua-Dateien. Wähle eine Datei direkt aus oder ändere den Lua-Ordner in den Einstellungen."},
    {"脚本可在末尾返回一个清理函数；停止或重载时会调用它。没有清理函数的脚本无法自动撤销已经注册的事件。", "A script may return a cleanup function at the end; it is called when stopping or reloading. Scripts without one cannot automatically undo registered events.", "Скрипт может вернуть функцию очистки в конце; она вызывается при остановке или перезагрузке. Без неё зарегистрированные события нельзя отменить автоматически.", "Ein Skript kann am Ende eine Bereinigungsfunktion zurückgeben; sie wird beim Stoppen oder Neuladen aufgerufen. Ohne sie lassen sich registrierte Ereignisse nicht automatisch rückgängig machen."},
    {"提升 1 级", "Raise 1 Level", "Повысить на 1", "1 Stufe erhöhen"},
    {"一次升满", "Max Level", "Макс. уровень", "Maximieren"},
    {"物品筛选与生成", "Item Filter & Spawn", "Фильтр и создание", "Item-Filter & Erzeugung"},
    {"搜索物品名称或完整类型", "Search item name or full type", "Поиск предмета или типа", "Itemname oder Typ suchen"},
    {"全部", "All", "Все", "Alle"},
    {"其他", "Other", "Другое", "Sonstiges"},
    {"游戏原生", "Game Native", "Оригинал игры", "Spiel-Original"},
    {"原生", "Native", "Оригинал", "Original"},
    {"仅单机，支持全部物品", "Single-player only; supports every item", "Только одиночная игра; все предметы", "Nur Einzelspieler; unterstützt alle Items"},
    {"联机取物", "Online Retrieve", "Получение по сети", "Online-Abruf"},
    {"自动选择可用联机路径", "Automatically selects an available online route", "Автоматически выбирает доступный сетевой способ", "Wählt automatisch einen verfügbaren Online-Weg"},
    {"自动选择可用联机路径，仅支持背包", "Automatically selects an online route; inventory only", "Автоматически выбирает сетевой способ; только инвентарь", "Wählt automatisch einen Online-Weg; nur Inventar"},
    {"联机取物仅支持背包，不能生成到地面", "Online Retrieve only supports the inventory; ground spawning is unavailable", "Получение по сети поддерживает только инвентарь; создание на земле недоступно", "Online-Abruf unterstützt nur das Inventar; Erzeugen auf dem Boden ist nicht verfügbar"},
    {"尸体载荷", "Corpse Payload", "Груз в трупе", "Leichen-Nutzlast"},
    {"尸体", "Corpse", "Труп", "Leiche"},
    {"在脚下投递服务器僵尸尸体", "Deliver a server zombie corpse at your feet", "Доставить серверный труп зомби к ногам", "Server-Zombieleiche zu deinen Füßen ablegen"},
    {"服装变体", "Clothing Variant", "Вариант одежды", "Kleidungsvariante"},
    {"变体", "Variant", "Вариант", "Variante"},
    {"带外观数据的服装物品", "Clothing items with appearance data", "Одежда с данными внешнего вида", "Kleidungsstücke mit Aussehensdaten"},
    {"陷阱猎物", "Trap Prey", "Добыча ловушки", "Fallenbeute"},
    {"可由陷阱登记的食物", "Food that can be registered by a trap", "Еда, которую может зарегистрировать ловушка", "Von einer Falle registrierbare Nahrung"},
    {"武器陷阱", "Weapon Trap", "Оружие-ловушка", "Waffenfalle"},
    {"武器", "Weapon", "Оружие", "Waffe"},
    {"安全的武器物品", "Safe weapon items", "Безопасные предметы-оружие", "Sichere Waffenobjekte"},
    {"弹药拆出", "Extract Ammo", "Извлечь патроны", "Munition entnehmen"},
    {"卸弹", "Unload", "Разрядить", "Entladen"},
    {"兼容枪械的散装弹药", "Loose ammo from compatible firearms", "Рассыпные патроны совместимого оружия", "Lose Munition kompatibler Schusswaffen"},
    {"弹匣拆出", "Extract Magazine", "Извлечь магазин", "Magazin entnehmen"},
    {"退匣", "Magazine", "Магазин", "Magazin"},
    {"兼容外置弹匣", "Compatible detachable magazine", "Совместимый съёмный магазин", "Kompatibles abnehmbares Magazin"},
    {"配件拆出", "Detach Part", "Снять модуль", "Anbauteil entfernen"},
    {"配件", "Part", "Модуль", "Anbauteil"},
    {"带挂载点的武器配件", "Weapon parts with mount points", "Оружейные детали с точками крепления", "Waffenteile mit Befestigungspunkten"},
    {"联机", "Online", "Сеть", "Online"},
    {"联机取物，支持有效物品", "Online retrieval for valid items", "Получение доступных предметов по сети", "Online-Abruf für gültige Items"},
    {"已进入联机会话，默认使用联机取物", "Network session detected; using Online Retrieve by default", "Обнаружен сетевой сеанс; по умолчанию используется получение по сети", "Online-Sitzung erkannt; standardmäßig wird Online-Abruf verwendet"},
    {"当前为本地会话，默认使用游戏原生", "Local session detected; using Game Native by default", "Локальный сеанс; по умолчанию выбран оригинал игры", "Lokale Sitzung erkannt; standardmäßig Spiel-Original"},
    {"未选择方案", "No method selected", "Способ не выбран", "Keine Methode ausgewählt"},
    {"全部方案", "All methods", "Все способы", "Alle Methoden"},
    {"已选 %d 个方案", "%d methods selected", "Выбрано способов: %d", "%d Methoden ausgewählt"},
    {"全部打开", "Enable All", "Включить все", "Alle aktivieren"},
    {"清空选择", "Clear Selection", "Очистить выбор", "Auswahl leeren"},
    {"已选择 %zu 项", "%zu items selected", "Выбрано: %zu", "%zu Items ausgewählt"},
    {"当前选择的方案不支持该物品", "The selected methods do not support this item", "Выбранные способы не поддерживают этот предмет", "Die ausgewählten Methoden unterstützen dieses Item nicht"},
    {"当前路径：%s  ·  %s", "Current route: %s  ·  %s", "Текущий путь: %s  ·  %s", "Aktueller Pfad: %s  ·  %s"},
    {"可用物品 · %zu", "Available items · %zu", "Доступные предметы · %zu", "Verfügbare Items · %zu"},
    {"数量", "Quantity", "Количество", "Anzahl"},
    {"生成到", "Spawn To", "Создать в", "Erzeugen in"},
    {"脚下僵尸尸体", "Zombie Corpse at Your Feet", "Труп зомби у ног", "Zombieleiche zu deinen Füßen"},
    {"当前路径：尸体载荷  ·  已选择 %zu 种物品", "Current route: Corpse Payload  ·  %zu item types selected", "Текущий путь: груз в трупе  ·  выбрано типов: %zu", "Aktueller Pfad: Leichen-Nutzlast  ·  %zu Itemtypen ausgewählt"},
    {"当前方案下没有匹配物品，请调整方案或搜索条件。", "No matching items for this method. Adjust the method or search.", "Для этого способа нет подходящих предметов. Измените способ или поиск.", "Keine passenden Items für diese Methode. Passe Methode oder Suche an."},
    {"尸体载荷清单", "Corpse Payload List", "Список груза в трупе", "Leichen-Nutzlastliste"},
    {"吸附", "Attach", "Прикрепить", "Andocken"},
    {"已吸附", "Attached", "Прикреплено", "Angedockt"},
    {"隐藏", "Hide", "Скрыть", "Ausblenden"},
    {"已选择 %zu 种", "%zu types selected", "Выбрано типов: %zu", "%zu Typen ausgewählt"},
    {"全部取消", "Clear All", "Отменить всё", "Alle entfernen"},
    {"取消", "Remove", "Убрать", "Entfernen"},
    {"拖动顶部可移动，靠近主窗口会自动吸附", "Drag the header to move; it attaches near the main window", "Перетащите заголовок; рядом с главным окном панель прикрепится", "Kopfzeile ziehen; nahe dem Hauptfenster wird die Leiste angedockt"},
    {"背包", "Inventory", "Инвентарь", "Inventar"},
    {"地面", "Ground", "Земля", "Boden"},
    {"快速测试 ×1", "Quick Test ×1", "Быстрый тест ×1", "Schnelltest ×1"},
    {"执行方案", "Execute", "Выполнить", "Ausführen"},
    {"暂无配置", "No configurations", "Нет конфигураций", "Keine Konfigurationen"},
    {"搜索名称或 ID", "Search name or ID", "Поиск имени или ID", "Name oder ID suchen"},
    {"药效", "Medication", "Эффекты лекарств", "Medikamente"},
    {"角色属性", "Character Stats", "Характеристики", "Charakterwerte"},
    {"属性", "Attribute", "Параметр", "Attribut"},
    {"当前", "Current", "Текущее", "Aktuell"},
    {"范围", "Range", "Диапазон", "Bereich"},
    {"应用", "Apply", "Применить", "Anwenden"},
    {"移除", "Remove", "Удалить", "Entfernen"},
    {"重置", "Reset", "Сбросить", "Zurücksetzen"},
    {"持续时间", "Duration", "Длительность", "Dauer"},
    {"效果强度", "Effect Strength", "Сила эффекта", "Effektstärke"},
    {"当前值", "Current Value", "Текущее значение", "Aktueller Wert"},
    {"选择上方状态以编辑", "Select a status above", "Выберите статус выше", "Oben einen Status wählen"},
    {"没有匹配的状态", "No matching status", "Статус не найден", "Kein Status gefunden"},
    {"服务器服药", "Server Medication", "Лекарство сервера", "Server-Medikament"},
    {"服务器应用", "Server Apply", "Применить на сервере", "Server anwenden"},
    {"同步应用", "Sync Apply", "Синхронно применить", "Synchron anwenden"},
    {"本地应用", "Local Apply", "Локально применить", "Lokal anwenden"},
    {"等待更新", "Awaiting Update", "Ожидание обновления", "Update ausstehend"},
    {"停止训练", "Stop Training", "Остановить тренировку", "Training stoppen"},
    {"低频训练", "Low-rate Training", "Редкая тренировка", "Langsames Training"},
    {"广播训练", "Broadcast Training", "Радиотренировка", "Sendetraining"},
    {"打开目录", "Open Folder", "Открыть папку", "Ordner öffnen"},
    {"删除", "Delete", "Удалить", "Löschen"},
    {"确认删除", "Confirm Delete", "Подтвердить удаление", "Löschen bestätigen"},
    {"确定", "Confirm", "Подтвердить", "Bestätigen"},
    {"取消", "Cancel", "Отмена", "Abbrechen"},
    {"确定删除选中的配置吗？", "Delete the selected configuration?", "Удалить выбранную конфигурацию?", "Ausgewählte Konfiguration löschen?"},
    {"配置已删除", "Configuration deleted", "Конфигурация удалена", "Konfiguration gelöscht"},
    {"联机添加经验目前会被检测，等待后续更新", "Online XP editing is detected; awaiting an update", "Изменение опыта в сети обнаруживается; ожидается обновление", "Online-EP werden erkannt; Update ausstehend"},
    {"显示全部能力范围", "Show all supported methods", "Показать все доступные методы", "Alle unterstützten Methoden anzeigen"},
    {"正在读取游戏物品目录，请稍后重试。", "Reading the game item catalog; try again shortly.", "Чтение каталога предметов; повторите позже.", "Itemkatalog wird gelesen; bitte später erneut versuchen."},
    {"当前方案组合下没有匹配物品，请调整多选方案或搜索条件。", "No items match the selected methods and search.", "Нет предметов для выбранных методов и поиска.", "Keine Items entsprechen Methoden und Suche."},
};

}  // namespace

Language GetLanguage() {
    return g_language;
}

void SetLanguage(Language language) {
    const auto value = static_cast<std::uint32_t>(language);
    g_language = value < static_cast<std::uint32_t>(Language::Count)
        ? language
        : Language::Chinese;
}

const char* LanguageName(Language language) {
    switch (language) {
        case Language::Chinese: return "中文";
        case Language::English: return "English";
        case Language::Russian: return "Русский";
        case Language::German: return "Deutsch";
        case Language::Count: break;
    }
    return "中文";
}

const char* Translate(const char* chinese_source) {
    if (chinese_source == nullptr || g_language == Language::Chinese) {
        return chinese_source;
    }
    for (const Translation& entry : kTranslations) {
        if (std::strcmp(entry.zh, chinese_source) != 0) continue;
        switch (g_language) {
            case Language::English: return entry.en;
            case Language::Russian: return entry.ru;
            case Language::German: return entry.de;
            default: return entry.zh;
        }
    }
    return chinese_source;
}

}  // namespace pztrainer::settings
